version: '3.4'

services:
  paymenthistory.api:
    image: ${DOCKER_REGISTRY-}paymenthistoryapi
    build:
      context: .
      dockerfile: PaymentHistory.API/Dockerfile
    depends_on:
      - db
      - dbmigration
  dbmigration:
    build:
      context: .
      dockerfile: Migrations/Dockerfile
    environment:
        SA_USER: "sa"
        SA_PASSWORD: "MyPassword001"
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      SA_PASSWORD: "MyPassword001"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"